"""Executable transitions shared with the replay diagram."""
STATES = {
    'act': ('通常：結果解釈＋次の1操作', 'llm', 1360, 300),
    'observe': ('画面・受付・実測', 'host', 40, 50),
    'understand': ('熟考：状況理解', 'llm', 370, 50),
    'backchain': ('熟考：前提条件を逆算', 'llm', 700, 50),
    'candidates': ('暫定：動詞と対象の候補生成', 'llm', 1360, 50),
    'ground': ('熟考：実行手順へ具体化', 'llm', 1030, 50),
    'reconcile': ('熟考：結果照合・更新', 'llm', 370, 300),
    'read_memory': ('旧比較：記憶の選択 / 8', 'llm', 700, 300),
    'choose_skill': ('旧比較：スキル選択 / 8', 'llm', 1030, 300),
    'execute_step': ('高速：操作 / 7 / 8', 'llm', 700, 530),
    'aim': ('高速：照準 / 7 / 8', 'llm', 1030, 530),
    'wait': ('操作送信・観測待ち', 'host', 40, 300),
    'stop': ('終了・期限・受付による停止', 'terminal', 40, 530),
    'answer_question': ('高速：測定変化の意味を質問', 'llm', 370, 530),
}
TRANSITIONS = {
    'direct_received': ('observe','act','現在の観測と直前の結果','normal'),
    'direct_accepted': ('act','wait','操作を直接実行・クリックはマスク内','normal'),
    'repair_act': ('act','act','出力契約の修正は最大1回','recovery'),
    'invalid_act': ('act','stop','出力契約エラー','stop'),
    "compact_backchained": ("backchain","candidates","小目標から抽象操作候補へ","normal"),
    "scene_candidates": ("understand","candidates","現在の対象を再取得","normal"),
    "candidates_ready": ("candidates","ground","最大3候補から行動計画","normal"),
    "candidates_missing": ("candidates","understand","対象情報の不足","recovery"),
    "focused_grounded": ("ground","execute_step","選択した手順を起動","normal"),
    "repair_candidates": ("candidates","candidates","候補の出力修正","recovery"),
    "invalid_candidates": ("candidates","stop","候補の出力契約エラー","stop"),
    'objects_uncertain': ('execute_step','reconcile','測定・対応に保留あり','recovery'),
    'questions_for_execution': ('execute_step','answer_question','測定変化と期待効果を照合','normal'),
    'questions_for_review': ('reconcile','answer_question','照合前の短い意味質問','normal'),
    'next_semantic_question': ('answer_question','answer_question','次の変更候補','normal'),
    'questions_to_review': ('answer_question','reconcile','試行・保留・矛盾を照合','recovery'),
    'questions_to_execution': ('answer_question','execute_step','質問完了・既存手順を継続','normal'),
    'received': ('observe','understand','初期観測／境界','normal'),
    'understood': ('understand','backchain','対象と疑問から逆算','normal'),
    'direct_ground': ('understand','ground','一操作の試行／既知手順','normal'),
    'backchained': ('backchain','ground','選んだ小目標を具体化','normal'),
    'ground_understand': ('ground','understand','対象の再解釈が必要','recovery'),
    'ground_backchain': ('ground','backchain','前提条件の修正が必要','recovery'),
    'grounded': ('ground','choose_skill','具体的な対象・条件・操作','normal'),
    'execute': ('choose_skill','execute_step','起動IDを付けて開始','normal'),
    'accepted': ('execute_step','wait','合法な操作を選択','normal'),
    'aim_started': ('execute_step','aim','意味で指定したクリック対象を探す','normal'),
    'aim_adjusted': ('aim','aim','領域選択／照準・拡大調整（ゲーム操作なし）','normal'),
    'aim_clicked': ('aim','wait','7：現在の照準をクリック','normal'),
    'aim_reconsider': ('aim','reconcile','8：対象不明／曖昧／再解釈','recovery'),
    'next_observation': ('wait','observe','受付と次の観測','normal'),
    'continue_execution': ('observe','execute_step','現在の手順を継続','normal'),
    'probe_observed': ('observe','reconcile','試行結果を取得（達成とは別）','normal'),
    'skill_reconsider': ('choose_skill','reconcile','8：適用できない／判断不能','recovery'),
    'step_reconsider': ('execute_step','reconcile','8：予想外／判断不能','recovery'),
    'step_done': ('execute_step','execute_step','7：手続き内の次の段階','normal'),
    'procedure_done': ('execute_step','reconcile','7：小目標の完了候補','normal'),
    'review_understand': ('reconcile','understand','対象・目標解釈を更新','recovery'),
    'review_backchain': ('reconcile','backchain','前提・小目標を更新','normal'),
    'review_ground': ('reconcile','ground','次の手順／局所修正','normal'),
    'review_resume': ('reconcile','execute_step','未完了の手順を継続','normal'),
    'repair_understand': ('understand','understand','理解の出力修正','recovery'),
    'repair_backchain': ('backchain','backchain','依存関係の出力修正','recovery'),
    'repair_ground': ('ground','ground','手順の出力修正','recovery'),
    'repair_reconcile': ('reconcile','reconcile','照合の出力修正','recovery'),
    'invalid_understand': ('understand','stop','理解の出力契約エラー','stop'),
    'invalid_backchain': ('backchain','stop','依存関係の出力契約エラー','stop'),
    'invalid_ground': ('ground','stop','手順の出力契約エラー','stop'),
    'invalid_reconcile': ('reconcile','stop','照合の出力契約エラー','stop'),
    'read_for_understand': ('understand','read_memory','理解の問いに必要な記録','normal'),
    'read_for_backchain': ('backchain','read_memory','逆算の問いに必要な記録','normal'),
    'read_for_ground': ('ground','read_memory','手順化の問いに必要な記録','normal'),
    'read_for_reconcile': ('reconcile','read_memory','結果照合に必要な記録','normal'),
    'memory_navigation': ('read_memory','read_memory','開く・採用・除外・ページ移動','normal'),
    'memory_to_understand': ('read_memory','understand','選んだ記録を渡す','normal'),
    'memory_to_backchain': ('read_memory','backchain','選んだ記録を渡す','normal'),
    'memory_to_ground': ('read_memory','ground','選んだ記録を渡す','normal'),
    'memory_to_reconcile': ('read_memory','reconcile','選んだ記録を渡す','normal'),
}
GLOBAL_GATES = [
    '通常は理解・コンパクト逆算・暫定候補生成・具体化・結果照合。旧比較経路も再生用に表示',
    '高速は1トークン。8は結果照合へ。7の小目標完了は確認前の候補',
    '通常の試行は複数操作を許容。旧比較の一操作試行は受付後に照合。試行終了と目標達成は別',
    '概念・役割の仮説と意味による対象指定を保持。座標は実行時に照準で確定',
    '照準は観測ごとに再取得。ホストのカーソル移動はゲームの操作・変化に含めない',
    '同条件の反復拒否なし。合法操作・観測ID・受付・実時間予算を検証',
    '実測とモデル解釈を区別して保持。通常経路では汎用ノート巡回を使わない',
]


def destination(event):
    return TRANSITIONS[event][1]
